apiVersion: v1
kind: Namespace
metadata:
  name: clamav
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clammer-deployment
  namespace: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clammer
  template:
    metadata:
      labels:
        app: clammer
    spec:
      containers:
      - name: clammer
        image: ghcr.io/ch0ppy35/clammer:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: clamav-volume
          mountPath: /clamav
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: clamav-volume
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-pvc
  namespace: clamav
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clammer-service
  namespace: clamav
spec:
  selector:
    app: clammer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
